
title: My Resume
url: 'http://junlulocky.com'
baseurl: 'hotttsaucePunkz/PanelCV' #change it according to your repository name



# Profile information
yourname: Miguel Almenara  ## put your name
title: 'Network Engineer'  ## your title
location: Miami , Fl


## Social Profiles
instagram: https://www.instagram.com/ltfrankdaabin
facebook: https://www.facebook.com/Zombiesallaround
twitter: http://www.twitter.com  ## your twitter account url
linkedin: https://www.linkedin.com/in/miguelalmenara
dribbble: http://www.dribble.com  ## you dribbble account url
foursquare: http://www.foursquare.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
